### ISSUE TITLE
Crash on Ubuntu 19.04

### ISSUE THREAD

**Issue by hcw70** [kmkolasinski/AwesomeBump#150]
when trying to compile / run on my ubuntu 1904 laptop i get a 
`"AwesomeBump" received signal SIGSEGV, Segmentation fault.
`

Compiled with ./unixBuildScript.sh (adapted to also have debug symbols) and launched via
`cd Bin/ ; ./AwesomeBump
`

from a checkout of commit 9f1049f8af30721a925916194d4994fea1a3d16b (master)
```
Author: kmkolasinski <kmkolasinski@gmail.com>
Date:   Sun Jun 25 18:58:01 2017 +0200

    Make AB compilable ....
```

Inspecting the crash with GDB gives:

ad 0x7fffea9ef700 (LWP 20638)]
```
Thread 1 "AwesomeBump" received signal SIGSEGV, Segmentation fault.
0x00005555555aefae in QVector<GLSLShaderParser*>::size (this=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:87
87	    inline int size() const { return d->size; }
(gdb) print d
Cannot access memory at address 0x0
(gdb) bt
#0  0x00005555555aefae in QVector<GLSLShaderParser*>::size() const (this=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:87
#1  0x000055555559ec91 in GLWidget::initializeGL() (this=0x555556af3860) at glwidget.cpp:248
#2  0x00007ffff7f2fbb5 in QGLWidget::glInit() () at /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#3  0x00007ffff7f333c0 in QGLWidget::resizeEvent(QResizeEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#4  0x00007ffff7a4953e in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff7a09551 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff7a10930 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff6daa8e9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff7a62def in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff7a665fd in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7a09551 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7a10930 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff6daa8e9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff74167f4 in QGuiApplicationPrivate::processGeometryChangeEvent(QWindowSystemInterfacePrivate::GeometryChangeEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#14 0x00007ffff7416a39 in QGuiApplicationPrivate::processWindowScreenChangedEvent(QWindowSystemInterfacePrivate::WindowScreenChangedEvent*)
    () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#15 0x00007ffff741b0c5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff73f505b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#17 0x00007ffff33db67a in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#18 0x00007ffff5de89ee in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x00007ffff5de8c88 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff5de8d1c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff6dfe0d4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00005555555b6864 in SplashScreen::setProgress(int) (this=0x7fffffffcff0, value=10) at main.cpp:144
#23 0x00005555555b5f27 in SplashScreen::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x7fffffffcff0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffce10) at main.moc:76
#24 0x00007ffff6dd4426 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00005555556f4a93 in MainWindow::initProgress(int) (this=0x7fffffffd030, _t1=10) at moc_mainwindow.cpp:430
#26 0x00005555555b7361 in MainWindow::initializeApp() (this=0x7fffffffd030) at mainwindow.cpp:58
#27 0x00005555555b5885 in main(int, char**) (argc=1, argv=0x7fffffffd288) at main.cpp:316

```

Any hints for this crash?

Kind regards

Hauke

**Comment by hcw70** [comment]
Ok, found the reason:

```
#define INIT_PROGRESS(p,m) \
	emit initProgress(p); \
    emit initMessage(m); \
    qApp->processEvents()

```

causes the crash....

When removing the content of that macro (so it is empty) the app works!

**Comment by hcw70** [comment]
Ok also it was not a good idea to go to master branch.... That issue (and other issues) seem to be resolved on "release" branch...

**Comment by kmkolasinski** [comment]
Hi, thanks for resolving this issue. I should remove that 'master' branch since it contains not working code and the name suggests a stable code. I will close this issue.

**Comment by kmkolasinski** [comment]
BTW: Could you try to use pre build binary package for ubuntu 18.04.
You can find it here: https://github.com/kmkolasinski/AwesomeBump/releases/tag/Linuxv5.1
I made this package today.

**Comment by hcw70** [comment]
Hmm. That binary crashes (with NVidia drivers enabled) under 19.04:

```
(gdb) r
Starting program: /home/hcw/tmp/Awe/AwesomeBump 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2303700 (LWP 10393)]
[New Thread 0x7fffebdee700 (LWP 10400)]
[New Thread 0x7fffeb5ed700 (LWP 10401)]
[New Thread 0x7fffeaaea700 (LWP 10402)]

Thread 1 "AwesomeBump" received signal SIGSEGV, Segmentation fault.
0x000000000042cffc in GLWidget::initializeGL() ()

```

My self-compiled version however runs ok.

Maybe you should link most stuff statically to ease migration.
Or even better, build a flatpak image?

```
hcw@nvidion:~/tmp/Awe$ ldd ./AwesomeBump
	linux-vdso.so.1 (0x00007ffca1313000)
	libQt5OpenGL.so.5 => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 (0x00007f6a729f1000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f6a7238e000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f6a71ddf000)
	libQt5Script.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Script.so.5 (0x00007f6a71b46000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f6a7161e000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f6a7158a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6a713a6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6a71258000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6a7123e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a71053000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6a71032000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f6a70ffb000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6a70fdd000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f6a70ee4000)
	libicui18n.so.63 => /usr/lib/x86_64-linux-gnu/libicui18n.so.63 (0x00007f6a70c09000)
	libicuuc.so.63 => /usr/lib/x86_64-linux-gnu/libicuuc.so.63 (0x00007f6a70a3a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6a70a34000)
	libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007f6a709b9000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f6a709a1000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f6a70880000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6a72ab5000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f6a7084c000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f6a7078f000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f6a706d4000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f6a706a5000)
	libicudata.so.63 => /usr/lib/x86_64-linux-gnu/libicudata.so.63 (0x00007f6a6ecb5000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f6a6ec41000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6a6eb07000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f6a6eade000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6a6e8d8000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f6a6e6d2000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f6a6e6b8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6a6e6ad000)

```

**Comment by kmkolasinski** [comment]
Hi thanks for checking this out, I'll give a try to flatpack then. This error you get is strange, though. I did all the previous versions in the same way and people were not complaining at all about such problem ... 
My ldd output is very similar, at first glance I don't see any difference there:
```
ldd ./AwesomeBump
	linux-vdso.so.1 (0x00007fff4e3f2000)
	libQt5OpenGL.so.5 => /opt/Qt5.9.0/5.9/gcc_64/lib/libQt5OpenGL.so.5 (0x00007fa2f94a4000)
	libQt5Widgets.so.5 => /opt/Qt5.9.0/5.9/gcc_64/lib/libQt5Widgets.so.5 (0x00007fa2f8c73000)
	libQt5Gui.so.5 => /opt/Qt5.9.0/5.9/gcc_64/lib/libQt5Gui.so.5 (0x00007fa2f84c6000)
	libQt5Script.so.5 => /opt/Qt5.9.0/5.9/gcc_64/lib/libQt5Script.so.5 (0x00007fa2f803e000)
	libQt5Core.so.5 => /opt/Qt5.9.0/5.9/gcc_64/lib/libQt5Core.so.5 (0x00007fa2f7906000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa2f767a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa2f72f1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa2f6f53000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa2f6d3b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa2f694a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa2f672b000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa2f650e000)
	libicui18n.so.56 => /opt/Qt5.9.0/5.9/gcc_64/lib/libicui18n.so.56 (0x00007fa2f6075000)
	libicuuc.so.56 => /opt/Qt5.9.0/5.9/gcc_64/lib/libicuuc.so.56 (0x00007fa2f5cbd000)
	libicudata.so.56 => /opt/Qt5.9.0/5.9/gcc_64/lib/libicudata.so.56 (0x00007fa2f42da000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa2f40d2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa2f3ece000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fa2f3ccc000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fa2f39b5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa2f9d62000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fa2f3784000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fa2f34ce000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa2f325c000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa2f2f24000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa2f2cfc000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa2f2af8000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa2f28f2000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa2f26dd000)
```

**Comment by hcw70** [comment]
If you provide a debug build i can tell you  the stack trace....

**Comment by kmkolasinski** [comment]
Do you use QtCreator ?

**Comment by hcw70** [comment]
I did compile my version via qmake / make. I had also look at it inside QtCreator debugging. But please note that my compiled version runs....

**Comment by kmkolasinski** [comment]
Yes I see, basically I except that one of the libraries I linked with the release is not compatible with your system, hence the segfault. Maybe we shouldn't worry about this.

**Comment by hcw70** [comment]
Maybe we (you) should worry about this since we have 2019 so Ubuntu 19.04 / 19.10 is the current version, and so either you can provide binaries for 19.04 also or your should provide binaries which also run on 19.04.

Else the conclusion would be for many user: "Doesnt run on Ubuntu".... 8-<

**Comment by kmkolasinski** [comment]
Probably you are right I will try to run AB on different ubuntu 18 and see whether this is related to versions or rather libraries.
